### PR TITLE
Dev level map

### PR DESCRIPTION
**Pull request by Cyberface**
So when making BAM h5 files I want to make sure that I use the largest available extraction radius.

This was basically impossible to do because the information about what the 'level' for a given extraction radius was, was not available.

This PR changes this. It modifies the BAM and MAYA handler to return an extraction_map_dictionary that has the same information about the extraction radius as before but also has the same thing but for the level. Note that MAYA doesn't actually use this so it's just set to None but has the same structure for homogeneity reasons.

Can you check if you are happy with this Lionel? Then merge? Thanks!

### CODE REVIEW

**Comment by llondon6** [comment]
Hi Sebastian,

It looks like this can be done with no code changes, thought is it a bit convoluted. See below:

```python
# Find an NR Simulation
sim_id = 'q18a0aM04c025_96_fine' 
A = scsearch(keyword=sim_id,verbose=True,apply_remnant_fit=True)[-1]
# Determine the maximum extraction radius using the extraction_radius_map
max_radius = max( A.extraction_radius_map.values() )
# Use the handler method to find the related level
extraction_parameter_for_max_radius,level_for_max_radius,extraction_radius_map = x.infer_default_level_and_extraction_parameter(A,desired_exraction_radius=max_radius,verbose=True)
print level_for_max_radius
# Load the simulation (look out for the correct file name in the print dialog)
y = gwylm(A,lm=(2,2),level=level_for_max_radius,clean=True,verbose=True,extraction_parameter=extraction_parameter_for_max_radius)
```

That said, I'll take a closer look at your code changes in a bit. I'll likely add them with minor modifications. I'd like to minimize the number related dictionaries if possible.

**Comment by Cyberface** [comment]
Ahhh that's how you can get to `infer_default_level_and_extraction_parameter`. You have to go through `A.loadhandler()`

Ok this is good because my way you have to recompile the catalogue :)

But I do like my way because then you have the information about the levels straight away.

maybe the following helper function is what's needed in maybe the bam.py handler?
```
def find_level(scentry, radius_number):
    x = scentry.loadhandler()
    radius_in_M = extraction_radius_map[radius_number]
    # Use the handler method to find the related level
    extraction_parameter_for_max_radius,level_for_radius,_ = x.infer_default_level_and_extraction_parameter(A,desired_exraction_radius=radius_in_M,verbose=True)
    print level_for_radius
    return level_for_radius
```

**Comment by llondon6** [comment]
hmm, I think that I flubbed up the code for extraction_radius_map ... It's probably supposed to be a dictionary between level number and extraction radius

I can't see a use for knowing the "radius_number" ... now shutting down for the night with orange flavored welsh cakes

**Comment by Cyberface** [comment]
I dunno, I would like to be able to know what code distance (in M) corresponds to which extraction radii number. Is there another way how to get that?

I am biased of course, I think my patch does things OK.

Hope the cakes of my home land are nice.

One thing I realised is that we currently don't have an automated way of choosing the best extraction radii. For example the largest extraction radii might actually have a lower resolution than a closer extraction radii :(.

Maybe such a thing should be build into the handlers at the catalogue creation stage?

**Comment by llondon6** [comment]
> I would like to be able to know what code distance (in M) corresponds to which extraction radii number. Is there another way how to get that?

Ah, yes. That's the purpose of `extraction_radius_map` in the scentry class

>  I think my patch does things OK.

I agree. I'll merge, but also make a note to myself to put everything in one dictionary rather than two, since the information about lev and radius will very often/always be used together.

> One thing I realised is that we currently don't have an automated way of choosing the best extraction radii. For example the largest extraction radii might actually have a lower resolution than a closer extraction radii :(.

Quite true. Is the resolution at each level stored somewhere? Is there a rule of thumb for which level is the best which can be coded?

> Maybe such a thing should be build into the handlers at the catalogue creation stage?

Indeed. It's rough that low level changes require catalog rebuilding -- isn't this is why people use json?

**Comment by Cyberface** [comment]
Thanks for accepting the PR.

I think moving to JSON / YAML would be nice. But I wonder how large the JSON file would be. But it would allow one to easily change / update things. I think that would come under 'nrutils version 2.0'

**Pull request merged**
