### PR TITLE
Update README.md - test commit

### PR DESCRIPTION
**Pull request by Cyberface**
testing that my commits are listed properly in the `contributions'

### CODE REVIEW

**Comment by Galadirith** [comment]
Looks good, when you compare a previous commit 2de2458f4109a which doesn't register as you, compared to 276b7b4 which does register as you 😄

**Comment by Cyberface** [comment]
👍

**Comment by Galadirith** [comment]
And this is the log I get when checking out `Cyberface/test-commit`

```
commit 276b7b4870630e8e6926dbb9454ad1c4b9e67331
Author: Sebastian Khan <Cyberface@users.noreply.github.com>
Date:   Mon Apr 11 13:36:38 2016 +0100

    Update README.md - test commit
    
    testing that my commits are listed properly in the `contributions'
```

Yeh 🎉

**Comment by Cyberface** [comment]
oh yEH!

On 11 April 2016 at 13:48, Edward Fauchon-Jones <notifications@github.com>
wrote:

> And this is the log I get when checking out Cyberface/test-commit
>
> commit 276b7b4870630e8e6926dbb9454ad1c4b9e67331
> Author: Sebastian Khan <Cyberface@users.noreply.github.com>
> Date:   Mon Apr 11 13:36:38 2016 +0100
>
>     Update README.md - test commit
>
>     testing that my commits are listed properly in the `contributions'
>
> Yeh 🎉
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/llondon6/nrutils_dev/pull/7#issuecomment-208322783>
>



-- 
Sebastian Khan
Postgraduate Student
Gravitational Physics Group

School of Physics & Astronomy
Queens Buildings, The Parade
Cardiff, CF24 3AA

Email: sebastian.khan@astro.cf.ac.uk
Phone: (+44) 29 208 75120

**Pull request merged**
